### ISSUE TITLE
what the hell with commands?

### ISSUE THREAD

**Issue by TheSirCororo** [jakobkmar/KSpigot#40]
```
org.bukkit.command.CommandException: Unhandled exception executing 'randomrush start' in org.bukkit.craftbukkit.v1_18_R1.command.VanillaCommandWrapper(randomrush)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:169) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchCommand(CraftServer.java:907) ~[paper-1.18.1.jar:git-Paper-205]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2289) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2100) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2081) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.a(ServerboundChatPacket.java:6) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.1.jar:git-Paper-205]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1414) ~[paper-1.18.1.jar:git-Paper-205]
        at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189) ~[paper-1.18.1.jar:git-Paper-205]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1391) ~[paper-1.18.1.jar:git-Paper-205]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1384) ~[paper-1.18.1.jar:git-Paper-205]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1362) ~[paper-1.18.1.jar:git-Paper-205]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1268) ~[paper-1.18.1.jar:git-Paper-205]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-205]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NoSuchMethodError: 'net.minecraft.commands.CommandSourceStack net.axay.kspigot.commands.CommandContext.getSender()'
        at ru.snappyland.randomrush.command.AdminCommandKt$settingAdminCommand$lambda-2$$inlined$runs$1.run(Execution.kt:50) ~[RandomRush-plugin-1.0.0.jar:?]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:263) ~[paper-1.18.1.jar:?]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:177) ~[paper-1.18.1.jar:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:291) ~[?:?]
        at org.bukkit.craftbukkit.v1_18_R1.command.VanillaCommandWrapper.execute(VanillaCommandWrapper.java:45) ~[paper-1.18.1.jar:git-Paper-205]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        ... 20 more
```
Code that causes error:
```kt
command(...) {
    // ...
    runs {
    // ...
        sender.bukkitSender.sendMessage(...)
    // ^       ^ error causes here
    }
}
```

**Comment by Krxwallo** [comment]
what do you have in your `build.gradle.kts`?

**Comment by jakobkmar** [comment]
There can be many reasons, maybe you forgot to provide KSpigot at runtime using the `libraries` section in your plugin.yml, or maybe you used the wrong jar which has not been remapped.

**Comment by TheSirCororo** [comment]
And my JAR contains KSpigot

**Comment by jakobkmar** [comment]
KSpigot is not meant to be put into your jar, you just have to add it to your libraries block.

**Comment by TheSirCororo** [comment]
It works incorrectly, I can't
