### ISSUE TITLE
Failed to Load Plugin on Server (NoClassDefFoundError)

### ISSUE THREAD

**Issue by Klebestreifen** [jakobkmar/KSpigot#57]
I am currently working on a plugin, however an error when loading the plugin is preventing me from implementing it.

### Log
```
[19:30:26 ERROR]: Error occurred while enabling Tavern v1.0-SNAPSHOT (Is it up to date?)
java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_19_R3/CraftServer
        at net.axay.kspigot.commands.internal.BrigardierSupport.resolveCommandManager(BrigardierSupport.kt:36) ~[?:?]
        at net.axay.kspigot.commands.internal.BrigardierSupport.registerAll$KSpigot(BrigardierSupport.kt:45) ~[?:?]
        at net.axay.kspigot.main.KSpigot.onEnable(KSpigot.kt:71) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:565) ~[paper-1.19.2.jar:git-Paper-307]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:479) ~[paper-1.19.2.jar:git-Paper-307]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.reload(CraftServer.java:1025) ~[paper-1.19.2.jar:git-Paper-307]
        at org.bukkit.Bukkit.reload(Bukkit.java:930) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:54) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:916) ~[paper-1.19.2.jar:git-Paper-307]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchServerCommand(CraftServer.java:879) ~[paper-1.19.2.jar:git-Paper-307]
        at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:500) ~[paper-1.19.2.jar:git-Paper-307]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.19.2.jar:git-Paper-307]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.2.jar:git-Paper-307]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.2.jar:git-Paper-307]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-307]
        at java.lang.Thread.run(Thread.java:1623) ~[?:?]
Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_19_R3.CraftServer
        at java.net.URLClassLoader.findClass(URLClassLoader.java:445) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        ... 20 more
[19:30:26 INFO]: [Tavern] Disabling Tavern v1.0-SNAPSHOT
[19:30:26 INFO]: [Tavern] Disabled
```
### plugin.yml
```yaml
name: Tavern
version: '${version}'
main: io.klebe.tavern.Plugin
api-version: 1.19
libraries:
  - "net.axay:kspigot:1.19.2"
commands:
  tavern:
    description: Tavern-Plugin Commands
    usage: /<command> <subcommand>

```
### build.gradle
```groovy
plugins {
    id 'idea'
    id 'java'
    id 'org.jetbrains.kotlin.jvm' version '1.8.10'
    //id 'com.github.johnrengelman.shadow' version '2.0.4'
    id 'io.papermc.paperweight.userdev' version "1.5.5"
}

group = 'io.klebe'
version = '1.0-SNAPSHOT'

idea {
    module {
        downloadJavadoc = true
        downloadSources = true
    }
}

repositories {
    mavenCentral()
    maven {
        name = 'papermc-repo'
        url = 'https://repo.papermc.io/repository/maven-public/'
    }
    maven {
        name = 'sonatype'
        url = 'https://oss.sonatype.org/content/groups/public/'
    }
    maven {
        url = "https://libraries.minecraft.net"
    }
}

dependencies {
    paperweight.paperDevBundle "1.19.4-R0.1-SNAPSHOT"
    implementation 'net.axay:kspigot:1.19.2'
}

def targetJavaVersion = 17
java {
    def javaVersion = JavaVersion.toVersion(targetJavaVersion)
    sourceCompatibility = javaVersion
    targetCompatibility = javaVersion
    if (JavaVersion.current() < javaVersion) {
        toolchain.languageVersion = JavaLanguageVersion.of(targetJavaVersion)
    }
}

tasks {
    build {
        dependsOn(reobfJar)
    }
    compileJava {
        options.encoding = "UTF-8"
        options.release.set targetJavaVersion
    }
    compileKotlin {
        kotlinOptions.jvmTarget = targetJavaVersion
    }
}

processResources {
    def props = [version: version]
    inputs.properties props
    filteringCharset 'UTF-8'
    filesMatching('plugin.yml') {
        expand props
    }
}
compileKotlin {
    kotlinOptions {
        jvmTarget = targetJavaVersion
    }
}
compileTestKotlin {
    kotlinOptions {
        jvmTarget = targetJavaVersion
    }
}

```

Server: Paper version git-Paper-307 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 476ef25)
Also tested with: `paper-1.19.4-550` and `paper-1.20.1-18` ~ same error

Is this a bug or did I miss something?

**Comment by jakobkmar** [comment]
KSpigot version `1.19.2` is for Minecraft `1.19.4` and does not support Minecraft `1.19.2`.

**Comment by Klebestreifen** [comment]
I have also tested

**Comment by Klebestreifen** [comment]
Okay, never mind, I switched back to the 1.19.4 jar, now it works...... I'm stupid.... sorry for the disturbance

**Comment by jakobkmar** [comment]
No problem, the version naming scheme is a bit confusing as well.
